# Generated by Django 3.2.8 on 2024-08-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('year_founded', models.IntegerField()),
                ('industry', models.CharField(max_length=100)),
                ('size_range', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('linkedin_url', models.URLField()),
                ('current_employee_estimate', models.IntegerField()),
                ('total_employee_estimate', models.IntegerField()),
            ],
        ),
    ]
